from tkinter import *
a=Tk()
a.title("my first window")
a.geometry("500x500+100+100")
m1=Menu()
l1=Menu()
l1.add_command(label="NewFile")
l1.add_command(label="OpenFile")
l1.add_command(label="SaveFile")
l1.add_command(label="SaveAs.....")
l1.add_command(label="PageSetup")
l1.add_command(label="Print....")
l1.add_command(label="Exit")
l2=Menu()
l2.add_command(label="Copy")
l2.add_command(label="Paste")
l2.add_command(label="Undo")
l2.add_command(label="Cut")
l2.add_command(label="Find Next.....")
l2.add_command(label="Replace")
l2.add_command(label="Go To")
l2.add_command(label="Select All....")
l2.add_command(label="Time/Date")
l3=Menu()
l3.add_command(label="Wordwrap")
l3.add_command(label="Font")
l4=Menu()
l4.add_command(label="Zoom")
l4.add_command(label="Statusbar")
l5=Menu()
l5.add_command(label="Viewhelp")
l5.add_command(label="Feedback")
l5.add_command(label="About Note")
m1.add_cascade(label="File",menu=l1)
m1.add_cascade(label="Edit",menu=l2)
m1.add_cascade(label="Format",menu=l3)
m1.add_cascade(label="View",menu=l4)
m1.add_cascade(label="Help",menu=l5)
a.config(menu=m1)
a.mainloop()